name: build-and-deploy
on:
  push:
    branches: [deployment]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install and verfiy sshpass
        run: |
          sudo apt install sshpass
          whereis sshpass
        shell: bash
      - name: SSH into Metropolia intranet
        env:
          USERNAME: ${{secrets.SSH_METROPOLIA_USERNAME}}
          SSHPASS: ${{secrets.SSH_METROPOLIA_PASSWORD}}
        run: |
          sshpass -e ssh -t "USERNAME@shell.metropolia.fi"
          whoami
        shell: bash
      - name: SSH into target server
        env:
          USERNAME: ${{secrets.SSH_SERVER_USERNAME}}
          SSHPASS: ${{secrets.SSH_SERVER_PASSWORD}}
        run: |
          sshpass -e ssh -t "USERNAME@shell.metropolia.fi"
          whoami
        shell: bash
