name: build-and-deploy
on:
  push:
    branches: [deployment]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install and verfiy sshpass
        run: |
          sudo apt install sshpass
          whereis sshpass
        shell: bash
      - name: SSH into Metropolia intranet
        env:
          SSH_METROPOLIA_USERNAME: ${{secrets.SSH_METROPOLIA_USERNAME}}
          SSH_METROPOLIA_PASSWORD: ${{secrets.SSH_METROPOLIA_PASSWORD}}
        run: |
          sshpass -p "$SSH_METROPOLIA_PASSWORD" ssh "$SSH_METROPOLIA_USERNAME@shell.metropolia.fi"
          whoami
        shell: bash
      - name: SSH into target server
        env:
          SSH_SERVER_USERNAME: ${{secrets.SSH_SERVER_USERNAME}}
          SSH_SERVER_PASSWORD: ${{secrets.SSH_SERVER_PASSWORD}}
        run: |
          sshpass -p "SSH_SERVER_PASSWORD" ssh "SSH_SERVER_USERNAME@shell.metropolia.fi"
          whoami
        shell: bash
