name: build-and-deploy
on:
  push:
    branches: [deployment]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install and verfiy sshpass
        run: |
          sudo apt install sshpass
          whereis sshpass
        shell: bash
      - name: SSH into Metropolia intranet
        run: |
          sudo sshpass -p "${{secrets.SSH_METROPOLIA_PASSWORD}}" ssh -vvv -o StrictHostKeyChecking=no -tt "${{secrets.SSH_METROPOLIA_USERNAME}}@shell.metropolia.fi"
          whoami
        shell: bash
      - name: SSH into target server
        env:
          USERNAME: ${{secrets.SSH_SERVER_USERNAME}}
          SSHPASS: ${{secrets.SSH_SERVER_PASSWORD}}
        run: |
          echo "$SSHPASS"
          sshpass -e ssh -vvv -o StrictHostKeyChecking=no -tt "USERNAME@shell.metropolia.fi"
          whoami
        shell: bash
