name: deploy
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy agora backend
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: "${{ secrets.SSH_SERVER_HOSTNAME }}"
          username: "${{ secrets.SSH_SERVER_USERNAME }}"
          password: "${{ secrets.SSH_SERVER_PASSWORD }}"
          proxy_host: "${{ secrets.SSH_PROXY_HOSTNAME }}"
          proxy_username: "${{ secrets.SSH_PROXY_USERNAME }}"
          proxy_password: "${{ secrets.SSH_PROXY_PASSWORD }}"
          debug: true
          script: |
            cd ~
            pm2 stop agora-backend
            mkdir tmp 
            mv agora-backend/uploads tmp/uploads
            rm -rf agora-backend
            git clone "${{ github.server_url }}/${{ github.repository }}.git"
            cd agora-backend
            cat > .env<< EOF
            # jsonwebtoken secret
            JWT_SECRET="${{ secrets.JWT_TOKEN }}"
            # frontend url
            FRONTEND_URL="http://${{ secrets.SSH_SERVER_HOSTNAME }}:3000"
            # mariadb connection credentials
            MARIADB_HOST="${{ secrets.MARIADB_HOSTNAME }}"
            MARIADB_USER="${{ secrets.MARIADB_USERNAME }}"
            MARIADB_PASSWORD="${{ secrets.MARIADB_PASSWORD }}"
            MARIADB_DATABASE="${{ secrets.MARIADB_DATABASE }}"
            EOF
            npm install
            npm run build
            cd ..
            mv tmp/uploads agora-backend/uploads
            rm -rf tmp
            pm2 start agora-backend/dist/server.js --name=agora-backend
